# permissions for end users to edit elasticsearchroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elasticsearchrole-editor-role
rules:
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchroles/status
  verbs:
  - get
