# permissions for end users to view elasticsearchwatchers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elasticsearchwatcher-viewer-role
rules:
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchwatchers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchwatchers/status
  verbs:
  - get
