# permissions for end users to view elasticsearchroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elasticsearchrole-viewer-role
rules:
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchroles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchroles/status
  verbs:
  - get
