# permissions for end users to view elasticsearchsnapshotrepositories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elasticsearchsnapshotrepository-viewer-role
rules:
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchsnapshotrepositories
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchsnapshotrepositories/status
  verbs:
  - get
