# permissions for end users to view elasticsearchilms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elasticsearchilm-viewer-role
rules:
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchilms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchilms/status
  verbs:
  - get
