# permissions for end users to view rolemappings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rolemapping-viewer-role
rules:
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - rolemappings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - rolemappings/status
  verbs:
  - get
