# permissions for end users to edit elasticsearchsnapshotrepositories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elasticsearchsnapshotrepository-editor-role
rules:
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchsnapshotrepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchsnapshotrepositories/status
  verbs:
  - get
