# permissions for end users to edit elasticsearchwatchers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elasticsearchwatcher-editor-role
rules:
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchwatchers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - elasticsearchwatchers/status
  verbs:
  - get
