# permissions for end users to view licenses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: license-viewer-role
rules:
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - licenses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - elk.k8s.webcenter.fr
  resources:
  - licenses/status
  verbs:
  - get
